[build]
  command = "npm run build && npm run export"
  publish = "out"

[dev]
  command = "npm run dev"

[functions]
  directory = "netlify/functions"

[context.production.environment]
  NEXT_PUBLIC_BASE_PATH = "/"
